openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
servers:
  - url: http://localhost:5001
    description: Local Development
  - url: https://lift-log.herokuapp.com
    description: Heroku Deployment
paths:
  /api/user/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Add your expected response properties here
                  exampleProperty:
                    type: string
        400:
          description: Bad Request
